"""add filters and keywords

Revision ID: add_filters_keywords
Revises: add_premium_end_date
Create Date: 2024-03-19 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_filters_keywords'
down_revision = 'add_premium_end_date'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('filters', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'keywords')
    op.drop_column('users', 'filters')
    # ### end Alembic commands ### 